name: EntityManager
main: milk\entitymanager\EntityManager

api: [4.0.0]
version: 2.0.0
load: STARTUP
author: LeinneSW
description: Control entity's function
website: https://github.com/LeinneSW/EntityManager

commands:
  entitymanager:
    description: control entity command
    aliases: ["entity", "ent", "em"]
    usage: "/entitymanager <remove/spawn/check>"
    permission: entitymanager.command

permissions:
  entitymanager.command:
    description: ""
    default: op